export const enum Categoria {
  VIRTUALIZACAO_DE_DESKTOP = 'VIRTUALIZACAO_DE_DESKTOP',

  VIRTUALIZACAO_DE_SERVIDORES = 'VIRTUALIZACAO_DE_SERVIDORES',

  VIRTUALIZACAO_DE_APLICACOES = 'VIRTUALIZACAO_DE_APLICACOES',

  MONITORAMENTO = 'MONITORAMENTO',

  EMAIL = 'EMAIL',

  MENSAGEM_INSTANTANEA = 'MENSAGEM_INSTANTANEA',

  TELEFONIA_FIXA = 'TELEFONIA_FIXA',

  TELEFONIA_MOVEL = 'TELEFONIA_MOVEL',

  INTERNET_MOVEL = 'INTERNET_MOVEL',

  IMPRESSAO = 'IMPRESSAO',

  CONECTIVIDADE = 'CONECTIVIDADE',

  COMPARTILHAMENTO_DE_ARQUIVOS = 'COMPARTILHAMENTO_DE_ARQUIVOS',

  HOSPEDAGEM_DE_WEBSITES = 'HOSPEDAGEM_DE_WEBSITES',

  HOSPEDAGEM_DE_APLICACOES = 'HOSPEDAGEM_DE_APLICACOES',

  DIRETORIO_USUARIOS = 'DIRETORIO_USUARIOS',

  BACKUP = 'BACKUP',
}
