package br.com.gerenciadordeincidente.domain.enumeration;

/**
 * The Categoria enumeration.
 */
public enum Categoria {
    VIRTUALIZACAO_DE_DESKTOP, VIRTUALIZACAO_DE_SERVIDORES, VIRTUALIZACAO_DE_APLICACOES, MONITORAMENTO, EMAIL, MENSAGEM_INSTANTANEA, TELEFONIA_FIXA, TELEFONIA_MOVEL, INTERNET_MOVEL, IMPRESSAO, CONECTIVIDADE, COMPARTILHAMENTO_DE_ARQUIVOS, HOSPEDAGEM_DE_WEBSITES, HOSPEDAGEM_DE_APLICACOES, DIRETORIO_USUARIOS, BACKUP
}
